# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Install terraform
        uses: hashicorp/setup-terraform@v1
        with:
           terraform_version: 0.14.7
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      
      - name: Terraform init
        id: init
        run: terraform init
        env:
           TF_VAR_GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
           TF_VAR_GIT_ORG : ${{ secrets.GIT_ORG  }}
      
      - name: Terraform apply
        id: plan
        run: terraform apply -auto-approve
        env:
           TF_VAR_GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
           TF_VAR_GIT_ORG : ${{ secrets.GIT_ORG  }}
           
